// Generated by CoffeeScript 1.3.3
(function() {
  var polyLoad;

  (polyLoad = function() {
    var MutationObserver;
    return Modernizr.load([
      {
        test: Modernizr.mq('only all'),
        yep: ['/static/stacks/js/file_ballet.js'],
        nope: ['/static/stacks/js/library/respond.min.js', '/static/stacks/ie8/ie8.css', '/static/stacks/ie8/ie8_fix.js', '/static/stacks/ie8/file_ballet_ie8.js'],
        complete: function() {
          return $(function() {
            var _this;
            _this = $("body");
            return _this.fileBallet();
          });
        }
      }, {
        test: MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver,
        yep: ['/static/stacks/js/flyout_dancer.js'],
        nope: ['/static/stacks/ie8/diving_tango.js']
      }, {
        test: Modernizr.multiplebgs,
        yep: ['/static/stacks/js/auto_run.js', '/static/stacks/js/faq_disco.js'],
        nope: ['/static/stacks/js/library/PIE.js', '/static/stacks/js/pie_load.js', '/static/stacks/ie8/faq_disco_ie8.js']
      }, {
        load: ['/static/stacks/css/xml_render.css', '/static/stacks/js/ajax_calls.js', '/static/stacks/js/library/jquery.lazyload.min.js'],
        complete: function() {
          var onLoadOptions, pageData, _this;
          _this = $("body");
          pageData = {
            objectType: _this.attr("data-object-type"),
            objectID: _this.attr("data-object-id"),
            userStatus: _this.attr("data-user-status")
          };
          if (pageData.userStatus === "staff") {
            onLoadOptions = {
              id: pageData.objectID,
              hierarchy: pageData.objectType
            };
            return _this.ajaxCalls({
              loadOptions: onLoadOptions
            });
          }
        }
      }
    ]);
  })();

}).call(this);
