// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var $, exports, gVars, myFunction, px;
    $ = require("jquery");
    exports = {};
    gVars = {};
    px = parseInt($("body").css("font-size"), 10);
    myFunction = function(vars) {
      console.log("passed variable: " + vars);
      console.log("set a global object literal gVars with init, " + gVars.myVar);
      return console.log("if I define something outside of functions,\nI can call on it,such as body's font-size: " + px + "px");
    };
    exports.myMethod = function(element) {
      return console.log("some other module is using me!");
    };
    exports.init = function(element) {
      var settings;
      settings = {
        var1: "foo",
        var2: "bar"
      };
      gVars.myVar = "foobar";
      console.log("myFunction init!");
      return myFunction(settings.var1);
    };
    return exports;
  });

}).call(this);
